### ISSUE TITLE
Boolean operations

### ISSUE THREAD

**Issue by Igres** [GLScene/GXScene#1]
Hello! A guide to class structure would be nice. In the meantime, the question of whether there is an implementation of Boolean operations on objects is of particular interest to the possibility of cutting another plane by a plane. Or getting the contour of the plane cut at a given height. Thank)

**Comment by GLScene** [comment]
Igres, look at and try to use Plane Functions and intersections in Scene.VectorGeometry unit. See also a shadedterrain project in GLScene's meshes demos. Pavel
